"""empty message

Revision ID: 91f7d687033d
Revises: 
Create Date: 2018-03-12 15:51:08.908079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91f7d687033d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('request_number', sa.String(length=20), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('uuidv4', sa.String(length=64), nullable=False),
    sa.Column('jobid', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('uuidv4'),
    sa.UniqueConstraint('request_number')
    )
    op.create_table('akamai_flush_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpcode', sa.String(length=45), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.uuidv4'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blocked_ip_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=16), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.uuidv4'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_address')
    )
    op.create_table('requestsor_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.uuidv4'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requestsor_emails')
    op.drop_table('blocked_ip_addresses')
    op.drop_table('akamai_flush_cache')
    op.drop_table('requests')
    # ### end Alembic commands ###
